# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|

    config.vm.box = 'precise64'
    config.vm.box_url = 'http://files.vagrantup.com/precise64.box'

    config.vm.hostname =  'dev'
    config.vm.network :private_network, ip: '11.11.11.11'
    
    config.vm.synced_folder '../', '/var/www', :nfs => true, :extra => 'dmode=777,fmode=777'

    config.vm.provider 'virtualbox' do |v|
        v.gui = false
        #v.name = 'bluecadet'
        #v.customize ['modifyvm', :id, '--rtcuseutc', 'on', "--ioapic", "on"]
        v.customize ['modifyvm', :id, '--rtcuseutc', 'on', '--ioapic', 'on', '--memory', '512']
    end

    config.vm.provision :shell, :inline => 'echo "America/New_York" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata'
    config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "puppet/manifests"
        puppet.manifest_file = "base.pp"
        puppet.module_path = "puppet/modules"
        # puppet.options = "--verbose --debug"
    end
end
